import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 10
builtin_box_drawing = true

# [font.offset]
# x = 2
# y = 1
#
# [font.glyph_offset]
# x = 4
# y = 1

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "0xProto Nerd Font Propo"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font Propo"
style = "Italic"

[font.bold_italic]
family = "0xProto Nerd Font Propo"
style = "Bold Italic"

[shell]
program = "/usr/bin/zsh"

[window.padding]
x = 5
y = 5
