# ~/.config/starship.toml

add_newline = false
command_timeout = 1000
format = """$os$username$hostname$kubernetes$directory$git_branch$git_status"""
#format = """$os$kubernetes$directory$git_branch$git_status"""

# Drop ugly default prompt characters
[character]
success_symbol = ''
error_symbol = ''

# ---

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'

# ---y

# Shows the username
[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = false

# Shows the hostname
[hostname]
ssh_only = true
format = 'on [$hostname](bold yellow) '
disabled = false
detect_env_vars = ['SSH_CONNECTION']

# Shows current directory
[directory]
truncation_length = 3
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
#format = 'at [$path]($style)[$read_only]($read_only_style) '
format = '[$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
symbol = ' '
#format = 'via [$symbol$branch]($style)'
format = '[$symbol$branch]($style) '
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
format = '([ $all_status$ahead_behind]($style) )'
style = 'bold green'
conflicted = '[](red) '
up_to_date = '[󰘽](green) '
untracked = '[󰋗 ${count}](red) '
ahead = ' ${count}'
diverged = ' ${ahead_count}  ${behind_count}'
behind = ' ${count}'
stashed = '[ ${count}](green) '
modified = '[󰛿 ${count}](yellow) '
staged = '[󰐗 ${count}](green) '
renamed = '[󱍸 ${count}](yellow) '
deleted = '[󰍶 ${count}](red) '

# Shows kubernetes context and namespace
[kubernetes]
format = '[󱃾 $context\($namespace\)](bold purple) '
disabled = false

# ---

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true
