#!/usr/bin/env bash
# keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

#picom
# Currently causes screen flickering
pkill picom
picom -b &

# monitors
#xrandr --output DP-0 --primary --below DP-4

# bsp config
if [[ $(xrandr -q | grep " connected" | wc -l) -gt 1 ]];
then
  MONITOR=$(xrandr -q | grep " connected" | grep -v "eDP-1" | awk '{print $1}')
  xrandr --output $MONITOR --auto --primary --mode 1920x1080 --pos 0x0  --rotate normal
  bspc monitor $MONITOR -d 0 1 2 3 4 5 6 7 8 9
else
  xrandr --output eDP-1  --primary --mode 1920x1080 --pos 0x0  --rotate normal
  bspc monitor eDP-1 -d 0 1 2 3 4 5 6 7 8 9
fi

bspc config border_width	2
bspc config window_gap		12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc config merge_overlapping_monitors true

bspc config normal_border_color "#394b70"
bspc config active_border_color "#3d59a1"
bspc config focused_border_color "#565f89"
bspc config presel_feedback_color "#bb9af7"

bspc rule -a kitty desktop=^2
bspc rule -a firefox desktop=^1
bspc rule -a discord desktop=^4
bspc rule -a Slack desktop=^4
bspc rule -a obsidian desktop=^3
bspc rule -a Zathura desktop=^3
bspc rule -a steam desktop=^5
bspc rule -a streaming_client desktop=^6

if [[ $(bspc query -D | wc -l) -gt 9 ]];
then
  bspc desktop Desktop --remove &
fi
# wallpaper
feh --bg-scale "$HOME/Pictures/Quantum Space.jpg"
# cursor move rate
xset r rate 200 40
# panel
$HOME/.config/polybar/launch.sh &
