#!/usr/bin/env bash
# keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

#picom
# Currently causes screen flickering
pkill picom
picom -CGb &

# monitors
#xrandr --output DP-0 --primary --below DP-4

# bsp config
if [[ $(xrandr -q | grep "DP-1-1 connected") ]];
then
  xrandr --output DP-1-1  --primary --mode 1920x1080 --pos 0x0  --rotate normal
  bspc monitor DP-1-1 -d 0 1 2 3 4 5 6 7 8 9
fi

bspc config border_width	2
bspc config window_gap		12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc config merge_overlapping_monitors true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

if [[ $(bspc query -D | wc -l) -gt 9 ]];
then
  bspc desktop Desktop --remove &
  bspc desktop 0 --remove &
fi
# wallpaper
feh --bg-scale $HOME/Downloads/dracula.png
# cursor move rate
xset r rate 200 40
# panel
$HOME/.config/polybar/launch.sh &
